# Getting MGnify datasets

The [MGnify API](https://www.ebi.ac.uk/metagenomics/api/v2/) provides access to MGnify analyses datasets and important metadata such as biome, sample, study, run, analysis details. 

```{margin}
After clicking the "Activate Notebook" button you can run the cells in this browser. Alternatively, you can also click on the 🚀 to launch in colab or binder.
```
<button title="Make live" style="display:inline-flex;align-items:center;gap:0.4rem;padding:0.5rem 1rem;border:0;border-radius:20px;background:linear-gradient(135deg,#0f766e,#14b8a6);color:white;cursor:pointer;font-size:1rem;" class="thebe-button" onclick="initThebeSBT()">Activate Notebook</button>

---

In [ ]:
# uncomment below if colab
#!pip install mgnipy



## 🎯 The Goal: Retrieve taxonomic datasets of tomato rhizosphere studies

Let's request tomato rhizosphere datasets and metadata from MGnify API.

Recall the typical workflow (from [What is MGni.Py?](https://mgnipy.mgnify.org/notebooks/getting-started/1_what_is_mgnipy.html)):

1. Start up a `mgnipy.MGnipy` client with your desired configuration

2. Search in MGnify resources using a MGnifier glass

3. Receive a MGazine of MGnify datasets

which we will follow in this notebook

In [1]:
from mgnipy import MGnipy

# 1. init with default config
MG = MGnipy(
    cache_dir="downloads"
)

# 2.a) setup studies mgnifier (build queries)
tomato_studies = MG.studies(
    biome_lineage="root:Host-associated:Plants:Rhizosphere", search="tomato"
)

In [3]:
with MG: 
    # 2.b) execute the list query (get the study list)
    tomato_studies.get_all()

    # 2.c) get the study list (execute all detail queries)
    tomato_studies.enrich_details()

# take a look at the studies details results as a pandas df
tomato_studies.metadata.to_pandas(expand_nested_dicts=True)

Retrieving studies pages: 100%|██████████| 1/1 [00:00<?, ?it/s]
Enriching study details: 100%|██████████| 17/17 [00:00<?, ?it/s]

Enriching study details: 100%|██████████| 17/17 [00:00<?, ?it/s]

,accession,ena_accessions,title,updated_at,downloads,first_accession,biome__biome_name,biome__lineage
0,MGYS00010296,"[ERP166137, PRJEB82448]",Microbiome-mediated tolerance of wild tomato t...,2026-05-28T15:46:48.615000+00:00,[],ERP166137,Rhizosphere,root:Host-associated:Plants:Rhizosphere
1,MGYS00010297,"[SRP333165, PRJNA755742]",Tomato rhizosphere microbiome in the pot exper...,2026-05-28T15:46:48.649000+00:00,[],SRP333165,Rhizosphere,root:Host-associated:Plants:Rhizosphere
2,MGYS00006231,"[ERP139927, PRJEB55060]",EMG produced TPA metagenomics assembly of PRJN...,2026-05-28T15:46:58.486000+00:00,"[{'file_type': 'tsv', 'download_type': 'Taxono...",ERP139927,Rhizosphere,root:Host-associated:Plants:Rhizosphere
3,MGYS00006204,"[ERP140102, PRJEB55219]",EMG produced TPA metagenomics assembly of PRJN...,2026-05-28T15:47:01.715000+00:00,"[{'file_type': 'tsv', 'download_type': 'Taxono...",ERP140102,Rhizosphere,root:Host-associated:Plants:Rhizosphere
4,MGYS00006205,"[ERP140107, PRJEB55224]",EMG produced TPA metagenomics assembly of PRJN...,2026-05-28T15:47:01.734000+00:00,"[{'file_type': 'tsv', 'download_type': 'Taxono...",ERP140107,Rhizosphere,root:Host-associated:Plants:Rhizosphere
5,MGYS00006208,"[ERP140115, PRJEB55232]",EMG produced TPA metagenomics assembly of PRJN...,2026-05-28T15:47:01.747000+00:00,"[{'file_type': 'tsv', 'download_type': 'Taxono...",ERP140115,Rhizosphere,root:Host-associated:Plants:Rhizosphere
6,MGYS00006230,"[ERP139923, PRJEB55057]",EMG produced TPA metagenomics assembly of PRJN...,2026-05-28T15:47:01.755000+00:00,"[{'file_type': 'tsv', 'download_type': 'Taxono...",ERP139923,Rhizosphere,root:Host-associated:Plants:Rhizosphere
7,MGYS00010257,"[SRP456588, PRJNA1004080]",Combined effect of microplastics and fungicide...,2026-05-28T15:46:48.538000+00:00,[],SRP456588,Soil,root:Host-associated:Plants:Rhizosphere:Soil
8,MGYS00010264,[PRJEB91717],Metagenome assembly of PRJNA1127303 data set (...,2026-05-28T15:46:48.743000+00:00,[],PRJEB91717,Soil,root:Host-associated:Plants:Rhizosphere:Soil
9,MGYS00010251,"[SRP338795, PRJNA766489]",Culture-independent analysis of rhizosphere mi...,2026-05-28T15:46:48.756000+00:00,[],SRP338795,Soil,root:Host-associated:Plants:Rhizosphere:Soil
10,MGYS00010245,"[PRJEB82447, ERP166136]",Unveiling diversity and adaptations of the wil...,2026-05-28T15:46:48.558000+00:00,[],ERP166136,Soil,root:Host-associated:Plants:Rhizosphere:Soil
11,MGYS00010324,[PRJEB95772],Metagenome assembly of PRJNA777724 data set (T...,2026-05-28T15:46:48.576000+00:00,[],PRJEB95772,Soil,root:Host-associated:Plants:Rhizosphere:Soil
12,MGYS00010258,"[SRP517058, PRJNA1127303]",Metagenomic data of rhizosphere soil during to...,2026-05-28T15:46:48.578000+00:00,[],SRP517058,Soil,root:Host-associated:Plants:Rhizosphere:Soil
13,MGYS00010298,"[PRJNA777724, SRP344777]",Tomato heritable microbiome,2026-05-28T15:46:48.670000+00:00,[],SRP344777,Soil,root:Host-associated:Plants:Rhizosphere:Soil
14,MGYS00010262,[PRJEB91684],Metagenome assembly of PRJNA1004080 data set (...,2026-05-28T15:46:48.688000+00:00,[],PRJEB91684,Soil,root:Host-associated:Plants:Rhizosphere:Soil
15,MGYS00010250,"[PRJNA755741, SRP333163]",Tomato rhizosphere microbiome in the belowgrou...,2026-05-28T15:46:48.730000+00:00,[],SRP333163,Soil,root:Host-associated:Plants:Rhizosphere:Soil
16,MGYS00010253,"[PRJNA789467, SRP351203]",Disentangling the genetic basis of rhizosphere...,2026-05-28T15:46:48.818000+00:00,[],SRP351203,Soil,root:Host-associated:Plants:Rhizosphere:Soil

## 3. Accessing the `MGazine` of datasets

- study details have a `mgnipy.MGazine` which allow us to download and interact with study-level datasets outputed from MGnify.

- We can use `mgnipy.MGazine` to download the datasets onto disk or read them into our notebook.

- To access the study's mgazine use `.datasets`

- the __str__ representaiton of mgazine gives us a peak into the pipeline versions within, number of downloads and the short_description categories

In [4]:
# access study mgazine
MZ = tomato_studies.datasets

# print for more info
print(MZ)

# also can view more as df
MZ.downloads_df()

MGazine containing:
- MGnify pipeline versions: ['v5']
- Number of downloads: 35
- Short descriptions: ['Complete GO annotation',
 'GO slim annotation',
 'InterPro matches',
 'Phylum level taxonomies LSU',
 'Phylum level taxonomies SSU',
 'Taxonomic assignments LSU',
 'Taxonomic assignments SSU']
- Nonempty metadata sets: .mgnify_studies

,file_type,download_type,short_description,long_description,alias,download_group,file_size_bytes,index_files,url,accession,pipeline_version
0,tsv,Taxonomic analysis,Phylum level taxonomies SSU,Phylum level taxonomies SSU (TSV),ERP139927_phylum_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
1,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP139927_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
2,tsv,Taxonomic analysis,Phylum level taxonomies LSU,Phylum level taxonomies LSU (TSV),ERP139927_phylum_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
3,tsv,Taxonomic analysis,Taxonomic assignments LSU,Taxonomic assignments LSU (TSV),ERP139927_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
4,tsv,Functional analysis,InterPro matches,InterPro matches (TSV),ERP139927_IPR_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
5,tsv,Functional analysis,GO slim annotation,GO slim annotation,ERP139927_GO-slim_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
6,tsv,Functional analysis,Complete GO annotation,Complete GO annotation,ERP139927_GO_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006231,v5
7,tsv,Taxonomic analysis,Phylum level taxonomies SSU,Phylum level taxonomies SSU (TSV),ERP140102_phylum_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
8,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP140102_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
9,tsv,Taxonomic analysis,Phylum level taxonomies LSU,Phylum level taxonomies LSU (TSV),ERP140102_phylum_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
10,tsv,Taxonomic analysis,Taxonomic assignments LSU,Taxonomic assignments LSU (TSV),ERP140102_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
11,tsv,Functional analysis,InterPro matches,InterPro matches (TSV),ERP140102_IPR_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
12,tsv,Functional analysis,GO slim annotation,GO slim annotation,ERP140102_GO-slim_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
13,tsv,Functional analysis,Complete GO annotation,Complete GO annotation,ERP140102_GO_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006204,v5
14,tsv,Taxonomic analysis,Phylum level taxonomies SSU,Phylum level taxonomies SSU (TSV),ERP140107_phylum_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
15,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP140107_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
16,tsv,Taxonomic analysis,Phylum level taxonomies LSU,Phylum level taxonomies LSU (TSV),ERP140107_phylum_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
17,tsv,Taxonomic analysis,Taxonomic assignments LSU,Taxonomic assignments LSU (TSV),ERP140107_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
18,tsv,Functional analysis,InterPro matches,InterPro matches (TSV),ERP140107_IPR_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
19,tsv,Functional analysis,GO slim annotation,GO slim annotation,ERP140107_GO-slim_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
20,tsv,Functional analysis,Complete GO annotation,Complete GO annotation,ERP140107_GO_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006205,v5
21,tsv,Taxonomic analysis,Phylum level taxonomies SSU,Phylum level taxonomies SSU (TSV),ERP140115_phylum_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
22,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP140115_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
23,tsv,Taxonomic analysis,Phylum level taxonomies LSU,Phylum level taxonomies LSU (TSV),ERP140115_phylum_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
24,tsv,Taxonomic analysis,Taxonomic assignments LSU,Taxonomic assignments LSU (TSV),ERP140115_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
25,tsv,Functional analysis,InterPro matches,InterPro matches (TSV),ERP140115_IPR_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
26,tsv,Functional analysis,GO slim annotation,GO slim annotation,ERP140115_GO-slim_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
27,tsv,Functional analysis,Complete GO annotation,Complete GO annotation,ERP140115_GO_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006208,v5
28,tsv,Taxonomic analysis,Phylum level taxonomies SSU,Phylum level taxonomies SSU (TSV),ERP139923_phylum_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5
29,tsv,Taxonomic analysis,Taxonomic assignments SSU,Taxonomic assignments SSU (TSV),ERP139923_taxonomy_abundances_SSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_ssu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5
30,tsv,Taxonomic analysis,Phylum level taxonomies LSU,Phylum level taxonomies LSU (TSV),ERP139923_phylum_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5
31,tsv,Taxonomic analysis,Taxonomic assignments LSU,Taxonomic assignments LSU (TSV),ERP139923_taxonomy_abundances_LSU_v5.0.tsv,study_summary.v5.0.taxonomic_analysis_lsu_rrna,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5
32,tsv,Functional analysis,InterPro matches,InterPro matches (TSV),ERP139923_IPR_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5
33,tsv,Functional analysis,GO slim annotation,GO slim annotation,ERP139923_GO-slim_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5
34,tsv,Functional analysis,Complete GO annotation,Complete GO annotation,ERP139923_GO_abundances_v5.0.tsv,study_summary.v5.0.functional_analysis,None,None,https://ftp.ebi.ac.uk/pub/databases/metagenomi...,MGYS00006230,v5

You can read in whole or stream in chunks a dataset by passing its `alias` or `url` to `MGazine.stream()`

In [5]:
MZ.stream(
    alias = MZ.aliases[5],
    chunksize=None, # default to read in all, set int for chunked reading
).head()

,GO,description,category,ERZ12343720,ERZ12343730,ERZ12343740,ERZ12343750,ERZ12343760,ERZ12343770,ERZ12343780,...,ERZ12590947,ERZ12593067,ERZ12590878,ERZ12590908,ERZ12590968,ERZ12590988,ERZ12590849,ERZ12590879,ERZ12590889,ERZ12590909
0,GO:0000015,phosphopyruvate hydratase complex,cellular component,106,77,69,106,96,88,102,...,107,103,57,84,70,76,97,79,148,94
1,GO:0000150,recombinase activity,molecular function,152,111,112,126,137,154,178,...,146,165,97,117,123,136,167,123,283,135
2,GO:0000160,phosphorelay signal transduction system,biological process,5337,4117,4340,5774,5273,5160,5794,...,5912,5731,2975,4728,4834,4776,5820,4669,8623,5539
3,GO:0000166,nucleotide binding,molecular function,27506,23975,22572,28502,28606,25597,30817,...,28526,31371,16457,25486,26749,23192,28760,24531,43168,29333
4,GO:0003674,molecular function,molecular function,3919,3307,3217,4040,3915,3621,4337,...,4138,4391,2305,3594,3695,3329,4124,3479,6271,4144

You can filter by short descriptioins by passing them as you would an index into square brackets i..e, __getitem__

In [6]:
ssu = MZ['Taxonomic assignments SSU']
print(ssu)

# now with additional taxonomic helpers
tax = ssu.taxonomic

MGazine containing:
- MGnify pipeline versions: ['v5']
- Number of downloads: 5
- Short descriptions: ['Taxonomic assignments SSU']
- Nonempty metadata sets: .mgnify_studies

TaxaMGazine containing:
- MGnify pipeline versions: ['v5']
- Number of downloads: 5
- Short descriptions: ['Taxonomic assignments SSU']
- Nonempty metadata sets: .mgnify_studies
-----------------------
Next steps: Use `.load()` to initialize.

The [MGazine informtion page](https://mgnipy.mgnify.org/notebooks/fundamentals/7_mgazine.html) also delves into how to download as well as other options for reading in the files

We will carry on with our filtered TaxaMGazine given [our goal](#-the-goal-retrieve-taxonomic-datasets-of-tomato-rhizosphere-studies) for now. 

for example, we can also combine the taxonomic assignment results into one dataframe e.g. `.to_pandas()`, `.to_polars`, `.X()`

In [7]:
# first loading
tax.load()

# accessing the 5 datasets in one df
tax.to_polars().head()

shape: (5, 150)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ taxonomy  ┆ ERZ123437 ┆ ERZ123437 ┆ ERZ123437 ┆ … ┆ ERZ126335 ┆ ERZ126335 ┆ ERZ125906 ┆ ERZ12590 │
│ ---       ┆ 20        ┆ 30        ┆ 40        ┆   ┆ 76        ┆ 79        ┆ 61        ┆ 669      │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ i64       ┆ i64       ┆ i64       ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ sk__Archa ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ null      ┆ null      ┆ 0         ┆ 2        │
│ ea        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ sk__Archa ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ ea;k__;p_ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _Crenarch ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ aeo…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ sk__Archa ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ ea;k__;p_ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _Crenarch ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ aeo…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ sk__Archa ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ ea;k__;p_ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _Thaumarc ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hae…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ sk__Archa ┆ 0         ┆ 1         ┆ 0         ┆ … ┆ 1         ┆ 2         ┆ 3         ┆ 3        │
│ ea;k__;p_ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _Thaumarc ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hae…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
# also as an annotated dataframe (AnnData)
tax.to_anndata()

WARNING:mgnipy.V2.datasets.annotate:No non-empty metadata sets available. Returning empty dataframe.
WARNING:mgnipy.V2.datasets.annotate:No non-empty metadata sets available. Returning empty dataframe.
/Users/anglup/GitHub/mgnipy/.venv/lib/python3.11/site-packages/legacy_api_wrap/__init__.py:88: UserWarning: X converted to numpy array with dtype float64
  return fn(*args_all, **kw)

AnnData object with n_obs × n_vars = 149 × 558
    var: 'Superkingdom', 'Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species'

We can see that only the `var` or features (taxonomy) are annotated. The `obs` or observations (runs/samples) are not yet annotated because we did not collect their metadata. 

From here we could use a `MGnetizer` to collect all the detailed metadata for the `.runs_accession` in our MGazine. See the following notebooks for more information

In [9]:
# tidying up cache
MG.clear_subcaches()

WARNING:mgnipy.mgnipy:Clearing ALL cache subdirectories in downloads

---

## Wrap Up:

This page was a quick start demonstration of:

1. ✅ Start up a `mgnipy.MGnipy` client with your desired configuration

2. ✅ Search in MGnify resources using a MGnifier glass

3. ✅ Receive a MGazine of MGnify datasets