# 🎁 Downloading MGnify Analyses for a given Study

<button title="Make live" style="display:inline-flex;align-items:center;gap:0.4rem;padding:0.5rem 1rem;border:0;border-radius:100px;background:linear-gradient(135deg,#0f766e,#14b8a6);color:white;box-shadow:0 6px 18px rgba(15,118,110,.25);cursor:pointer;font-size:1rem;" class="thebe-button" onclick="initThebeSBT()">Activate Notebook</button>

In this notebook, is starting code for retrieving all the MGnify Analyses for a given study accession. We use [MGYS00010442](https://www.ebi.ac.uk/metagenomics/v6-early-data-release/studies/MGYS00010442/overview) as an example. 

---

## 🎯 The Goal: View MGnify Analyses for study: [MGYS00010442](https://www.ebi.ac.uk/metagenomics/v6-early-data-release/studies/MGYS00010442/overview)

In this tutorial we demonstrate how MGni.py can be used to get MGnify Analyses datasets for a study.

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# uncomment below if colab
#!pip install mgnipy
#!pip install asyncio

In [3]:
# our study of interset
study_accession = "MGYS00010442"

## 🔎 Getting the Study's details
Here we import and configuire our MGnipy client

In [7]:
from mgnipy import MGnipy
import asyncio # optional, for async requests

# init
MG = MGnipy(
    #cache_dir="cache" # default dir is platform-specific,set to None to disable caching
)

# access study resource
study = MG.study(study_accession)

# check out call before making it
study.dry_run()

Planning the API call with params:
{'accession': 'MGYS00010442'}
Total requests to make: 1
Total records to retrieve: 1

let's go ahead and get the study's details:

In [8]:
# get
study.get()

# can clear cache now optionally or later or never
study.clear_cache()

# stored to results, so can view as list, dfs etc
study.to_df()

Advancing to request num 1

,accession,ena_accessions,title,biome,updated_at,downloads,metadata,first_accession
0,MGYS00010442,"[PRJEB37289, ERP120598]",TKI,"{'biome_name': 'Digestive system', 'lineage': ...",2026-04-21T08:55:57.196000+00:00,"[{'file_type': 'tsv', 'download_type': 'Taxono...",{},ERP120598

In [9]:
study.downloads

[{'file_type': 'tsv',
  'download_type': 'Taxonomic analysis',
  'short_description': 'Summary of DADA2-PR2 taxonomies',
  'long_description': 'Summary of DADA2-PR2 taxonomic assignments, across all runs in the study',
  'alias': 'ERP120598_DADA2-PR2_16S-V3-V4_study_summary.tsv',
  'download_group': 'study_summary.v6.amplicon',
  'file_size_bytes': None,
  'index_files': None,
  'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_DADA2-PR2_16S-V3-V4_study_summary.tsv',
  'accession': 'MGYS00010442'},
 {'file_type': 'tsv',
  'download_type': 'Taxonomic analysis',
  'short_description': 'Summary of PR2 taxonomies',
  'long_description': 'Summary of PR2 taxonomic assignments, across all runs in the study',
  'alias': 'ERP120598_PR2_study_summary.tsv',
  'download_group': 'study_summary.v6.amplicon',
  'file_size_bytes': None,
  'index_files': None,
  'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_PR2_study_summary.tsv',
  'accession': 'MGYS00010442'},
 {'file_type': 'tsv',
  'download_type': 'Taxonomic analysis',
  'short_description': 'Summary of DADA2-SILVA taxonomies',
  'long_description': 'Summary of DADA2-SILVA taxonomic assignments, across all runs in the study',
  'alias': 'ERP120598_DADA2-SILVA_16S-V3-V4_study_summary.tsv',
  'download_group': 'study_summary.v6.amplicon',
  'file_size_bytes': None,
  'index_files': None,
  'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_DADA2-SILVA_16S-V3-V4_study_summary.tsv',
  'accession': 'MGYS00010442'},
 {'file_type': 'tsv',
  'download_type': 'Taxonomic analysis',
  'short_description': 'Summary of SILVA-SSU taxonomies',
  'long_description': 'Summary of SILVA-SSU taxonomic assignments, across all runs in the study',
  'alias': 'ERP120598_SILVA-SSU_study_summary.tsv',
  'download_group': 'study_summary.v6.amplicon',
  'file_size_bytes': None,
  'index_files': None,
  'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_SILVA-SSU_study_summary.tsv',
  'accession': 'MGYS00010442'},
 {'file_type': 'csv',
  'download_type': 'Taxonomic analysis',
  'short_description': 'DwC-Ready summary of 16S-V3-V4 ASV taxonomies using -PR2 as ref DB',
  'long_description': 'DwC-Ready summary of 16S-V3-V4 ASV taxonomies using -PR2 as ref DB, across all runs in the study',
  'alias': 'ERP120598_DADA2-PR2_16S-V3-V4_dwcready.csv',
  'download_group': 'study_summary.v6.amplicon',
  'file_size_bytes': None,
  'index_files': None,
  'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_DADA2-PR2_16S-V3-V4_dwcready.csv',
  'accession': 'MGYS00010442'},
 {'file_type': 'csv',
  'download_type': 'Taxonomic analysis',
  'short_description': 'DwC-Ready summary of 16S-V3-V4 ASV taxonomies using -SILVA as ref DB',
  'long_description': 'DwC-Ready summary of 16S-V3-V4 ASV taxonomies using -SILVA as ref DB, across all runs in the study',
  'alias': 'ERP120598_DADA2-SILVA_16S-V3-V4_dwcready.csv',
  'download_group': 'study_summary.v6.amplicon',
  'file_size_bytes': None,
  'index_files': None,
  'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_DADA2-SILVA_16S-V3-V4_dwcready.csv',
  'accession': 'MGYS00010442'},
 {'file_type': 'csv',
  'download_type': 'Taxonomic analysis',
  'short_description': 'DwC-Ready summary of closed-ref taxonomies using SILVA-SSU as ref DB',
  'long_description': 'DwC-Ready summary of closed-reference taxonomies using SILVA-SSU as ref DB, across all runs in the study',
  'alias': 'ERP120598_closedref_SILVA-SSU_dwcready.csv',
  'download_group': 'study_summary.v6.amplicon',
  'file_size_bytes': None,
  'index_files': None,
  'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_closedref_SILVA-SSU_dwcready.csv',
  'accession': 'MGYS00010442'},
 {'file_type': 'csv',
  'download_type': 'Taxonomic analysis',
  'short_description': 'DwC-Ready summary of closed-ref taxonomies using PR2 as ref DB',
  'long_description': 'DwC-Ready summary of closed-reference taxonomies using PR2 as ref DB, across all runs in the study',
  'alias': 'ERP120598_closedref_PR2_dwcready.csv',
  'download_group': 'study_summary.v6.amplicon',
  'file_size_bytes': None,
  'index_files': None,
  'url': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_closedref_PR2_dwcready.csv',
  'accession': 'MGYS00010442'}]

## 📒 `MGazine` for accessing the study's datasets

- study details have a `mgnipy.MGazine` which allow us to download and interact with study-level datasets outputed from MGnify. 

- We can use `mgnipy.MGazine` to download the datasets onto disk or read them into our notebook. 

- To access the study's mgazine use `.datasets` 

- the str representaiton of mgazine tells us the number of download files and their {alias: url}

In [10]:
# getting mgazine
mgazine = study.datasets
# see info
print(mgazine)

MGazine with 8 downloads:
{'ERP120598_DADA2-PR2_16S-V3-V4_dwcready.csv': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_DADA2-PR2_16S-V3-V4_dwcready.csv',
 'ERP120598_DADA2-PR2_16S-V3-V4_study_summary.tsv': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_DADA2-PR2_16S-V3-V4_study_summary.tsv',
 'ERP120598_DADA2-SILVA_16S-V3-V4_dwcready.csv': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_DADA2-SILVA_16S-V3-V4_dwcready.csv',
 'ERP120598_DADA2-SILVA_16S-V3-V4_study_summary.tsv': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_DADA2-SILVA_16S-V3-V4_study_summary.tsv',
 'ERP120598_PR2_study_summary.tsv': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_PR2_study_summary.tsv',
 'ERP120598_SILVA-SSU_study_summary.tsv': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_SILVA-SSU_study_summary.tsv',
 'ERP120598_closedref_PR2_dwcready.csv': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_closedref_PR2_dwcready.csv',
 'ERP120598_closedref_SILVA-SSU_dwcready.csv': 'https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_results/ERP120/ERP120598/study-summaries/ERP120598_closedref_SILVA-SSU_dwcready.csv'}

### ⬇️ Downloading a copy of the files using `.download()` or `.download_all()`
- also with async support
- for downloading only need to pass a destination dir and the file alias (helper list `.aliases`) or url (helpers `.url_list`, `.url_dict`)

In [20]:
# check out file aliases
aa = mgazine.aliases

aa

['ERP120598_DADA2-PR2_16S-V3-V4_study_summary.tsv',
 'ERP120598_PR2_study_summary.tsv',
 'ERP120598_DADA2-SILVA_16S-V3-V4_study_summary.tsv',
 'ERP120598_SILVA-SSU_study_summary.tsv',
 'ERP120598_DADA2-PR2_16S-V3-V4_dwcready.csv',
 'ERP120598_DADA2-SILVA_16S-V3-V4_dwcready.csv',
 'ERP120598_closedref_SILVA-SSU_dwcready.csv',
 'ERP120598_closedref_PR2_dwcready.csv']

In [ ]:
# download one file by alias
mgazine.download(to_dir="downloads", alias=aa[1])

In [22]:
# downloading all, async optional
await mgazine.adownload_all(to_dir="downloads")

Overall Progress: 100%|==========| 8/8 [00:00<00:00, 871.93it/s]

### 📖 Alternatively, reading in the files using `stream`

- to continue working with the datasets before downloading
- support for csv/tsv (gzipped or not), txt, fasta, gff, biom, json, jsonl (see `mgnipy.V2.mixins.StreamMixin`)

In [23]:
mgazine.stream(alias=aa[1])

,taxonomy,ERR5382938,ERR5382939,ERR5382940,ERR5382941,ERR5382942,ERR5382943,ERR5382944,ERR5382945,ERR5382946,...,ERR5382991,ERR5382992,ERR5382993,ERR5382994,ERR5382995,ERR5382996,ERR5382997,ERR5382998,ERR5382999,ERR5383000
0,d__Archaea;sg__Methanoteca;dv__Euryarchaeota;s...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,d__Archaea;sg__Methanoteca;dv__Euryarchaeota;s...,2,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,2,0,0
2,d__Bacteria,1,0,1,9,0,0,0,0,2,...,0,0,1,0,0,0,0,0,0,0
3,d__Bacteria;sg__CCD;dv__Chloroflexi;sdv__Chlor...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,d__Bacteria;sg__CCD;dv__Patescibacteria;sdv__P...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374,d__Eukaryota:plas;sg__Archaeplastida:plas;dv__...,0,0,771,0,0,11,0,1,0,...,1,4,4,7,68,59,0,0,0,88
375,d__Eukaryota:plas;sg__Archaeplastida:plas;dv__...,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
376,d__Eukaryota:plas;sg__Archaeplastida:plas;dv__...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
377,d__Eukaryota:plas;sg__Haptista:plas,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
378,d__Eukaryota:plas;sg__TSAR:plas,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### TODO getting sample and analyses metadata

From the study detail we can list their analyses. We can check what other relationshiops are supported using `.list_relationships()`

In [4]:
study.list_relationships()

['samples', 'analyses', 'publications']