# Demo: Retrieving Mgnify tomato samples

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ebi-metagenomics/mgnipy/blob/main/docs/tutorial/demo-mgnify-tomatoes.ipynb)

In [ ]:
# uncomment below if colab
#!pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple mgnipy
#!pip install asyncio

In this tutorial we demonstrate how mgnipy can be used to retrieve tomato rhizosphere metagenomics analyses (only sample metadata for now) available on MGnify.

In [1]:
from mgnipy import MGnipy

you can either pass query parameters as dict to `params` or as kwargs. Please refer to [mgnify api docs](https://www.ebi.ac.uk/metagenomics/api/v2/) for the accepted kwargs for now or via attribute `Mgnifier.supported_kwargs`

In [2]:
# init 
MG = MGnipy(
    # configuration
)

# studies resource proxy
studies = MG.studies

# set up query
studies.filter(
    biome_lineage='root:Host-associated:Plants:Rhizosphere',
    search='tomato'
)

# make the get request
studies.get()

# look at results 
studies.to_pandas()

Planning the API call with params:
Response status code: 200
{'biome_lineage': 'root:Host-associated:Plants:Rhizosphere', 'search': 'tomato', 'page_size': 25}
Total pages to retrieve: 1
Total records to retrieve: 17
Retrieving first page of results for preview...
Response status code: 200
Page 1 already cached from preview, skipping...

Retrieving pages: 0it [00:00, ?it/s]

,accession,ena_accessions,title,biome,updated_at
0,MGYS00010296,"[ERP166137, PRJEB82448]",Microbiome-mediated tolerance of wild tomato t...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T14:00:52.352000+00:00
1,MGYS00010297,"[SRP333165, PRJNA755742]",Tomato rhizosphere microbiome in the pot exper...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:42:02.227000+00:00
2,MGYS00006204,"[ERP140102, PRJEB55219]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-01-27T16:27:14.469000+00:00
3,MGYS00006205,"[ERP140107, PRJEB55224]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-01-27T16:27:14.478000+00:00
4,MGYS00006208,"[ERP140115, PRJEB55232]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-01-27T16:27:14.505000+00:00
5,MGYS00006230,"[ERP139923, PRJEB55057]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-01-27T16:27:14.714000+00:00
6,MGYS00006231,"[ERP139927, PRJEB55060]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-01-27T16:27:14.722000+00:00
7,MGYS00010257,"[SRP456588, PRJNA1004080]",Combined effect of microplastics and fungicide...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-03T18:47:35.095000+00:00
8,MGYS00010258,"[SRP517058, PRJNA1127303]",Metagenomic data of rhizosphere soil during to...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-04T11:04:15.175000+00:00
9,MGYS00010324,[PRJEB95772],Metagenome assembly of PRJNA777724 data set (T...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-08-07T12:30:16.888000+00:00
10,MGYS00010245,"[PRJEB82447, ERP166136]",Unveiling diversity and adaptations of the wil...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-23T16:38:33.334000+00:00
11,MGYS00010298,"[PRJNA777724, SRP344777]",Tomato heritable microbiome,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-08-07T15:25:59.939000+00:00
12,MGYS00010262,[PRJEB91684],Metagenome assembly of PRJNA1004080 data set (...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-03T18:41:58.194000+00:00
13,MGYS00010250,"[PRJNA755741, SRP333163]",Tomato rhizosphere microbiome in the belowgrou...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-23T08:45:47.142000+00:00
14,MGYS00010264,[PRJEB91717],Metagenome assembly of PRJNA1127303 data set (...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-04T10:10:15.643000+00:00
15,MGYS00010251,"[SRP338795, PRJNA766489]",Culture-independent analysis of rhizosphere mi...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-21T17:01:18.132000+00:00
16,MGYS00010253,"[PRJNA789467, SRP351203]",Disentangling the genetic basis of rhizosphere...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-08-01T17:26:35.948000+00:00

In [3]:
# all samples for a given study above?
# first study 
second_study_samples = studies[1]
# or getitem by accession
# first_study_samples = studies["MGYS00010297"]

second_study_samples.get()
second_study_samples.to_pandas()

Planning the API call with params:
Response status code: 200
{'accession': 'MGYS00010297', 'page_size': 25}
Total pages to retrieve: 1
Total records to retrieve: 12
Retrieving first page of results for preview...
Response status code: 200
Page 1 already cached from preview, skipping...

Retrieving pages: 0it [00:00, ?it/s]

,accession,ena_accessions,sample_title,biome,updated_at,lat,lon
0,SRS9830941,"[SRS9830941, SAMN20841010]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.650000+00:00,45.41,126.37
1,SRS9830940,"[SRS9830940, SAMN20841019]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.685000+00:00,45.41,126.37
2,SRS9830946,"[SRS9830946, SAMN20841015]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.711000+00:00,45.41,126.37
3,SRS9830942,"[SRS9830942, SAMN20841011]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.736000+00:00,45.41,126.37
4,SAMN20841008,"[SAMN20841008, SRS9830937]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.761000+00:00,45.41,126.37
5,SRS9830948,"[SRS9830948, SAMN20841017]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.788000+00:00,45.41,126.37
6,SAMN20841016,"[SAMN20841016, SRS9830947]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.812000+00:00,45.41,126.37
7,SRS9830945,"[SRS9830945, SAMN20841014]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.837000+00:00,45.41,126.37
8,SAMN20841013,"[SAMN20841013, SRS9830944]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.861000+00:00,45.41,126.37
9,SRS9830943,"[SRS9830943, SAMN20841012]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.886000+00:00,45.41,126.37
10,SAMN20841018,"[SAMN20841018, SRS9830939]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.911000+00:00,45.41,126.37
11,SAMN20841009,"[SAMN20841009, SRS9830938]",None,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:25:30.939000+00:00,45.41,126.37