# 🕵️‍♀️ Searching for MGnify Studies

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ebi-metagenomics/mgnipy/blob/main/docs/tutorials/getting-started/demo-mgnify-tomatoes.ipynb)

On this page, which also serves as a runnable notebook (link above ^), we again demonstrate the basic usability of MGni.py to search the [Studies resource](https://www.ebi.ac.uk/metagenomics/api/v2/#/Studies/list_mgnify_studies) for some studies of interest (e.g., tomaotos)

---

## 🎯 The Goal: Get a list of MGnify studies of tomato rhizospheres

WIP

In [1]:
# uncomment below if colab
#!pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple mgnipy
#!pip install asyncio

In [2]:
from mgnipy import MGnipy

MG = MGnipy()

tomato_studies = MG.studies(
    biome_lineage="root:Host-associated:Plants:Rhizosphere", search="tomato"
)

# tomato_studies.explain()

Choose your entry resource proxy

In [3]:
# init
MG = MGnipy(
    # configuration
)

# helper
MG.list_resources()

['analyses',
 'analysis',
 'assemblies',
 'assembly',
 'genomes',
 'genome',
 'publications',
 'publication',
 'samples',
 'sample',
 'studies',
 'study',
 'runs',
 'run',
 'biomes',
 'biome',
 'catalogues',
 'catalogue',
 'annotations',
 'private_studies']

you can either pass query parameters as dict to `params` or as kwargs.

In [4]:
# studies resource proxy
studies = MG.studies

# helper
studies.list_supported_params()

['order',
 'biome_lineage',
 'has_analyses_from_pipeline',
 'search',
 'page',
 'page_size']

In [5]:
# set up query
filtered_studies = studies.filter(
    biome_lineage="root:Host-associated:Plants:Rhizosphere", search="tomato"
)

# preview before getting all pages
filtered_studies.dry_run()

Planning the API call with params:
{'biome_lineage': 'root:Host-associated:Plants:Rhizosphere', 'search': 'tomato'}
Total requests to make: 1
Total records to retrieve: 17

In [6]:
# make the get request
await filtered_studies.abulk_fetch()

# look at our list of studies
filtered_studies.to_df()

Retrieving pages: 100%|██████████| 1/1 [00:00<00:00, 1308.68it/s]

,accession,ena_accessions,title,biome,updated_at
0,MGYS00010296,"[ERP166137, PRJEB82448]",Microbiome-mediated tolerance of wild tomato t...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T14:00:52.352000+00:00
1,MGYS00010297,"[SRP333165, PRJNA755742]",Tomato rhizosphere microbiome in the pot exper...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:42:02.227000+00:00
2,MGYS00006231,"[ERP139927, PRJEB55060]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2026-04-30T22:27:28.963000+00:00
3,MGYS00006204,"[ERP140102, PRJEB55219]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2026-04-30T22:01:19.102000+00:00
4,MGYS00006205,"[ERP140107, PRJEB55224]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2026-04-30T22:01:31.666000+00:00
5,MGYS00006230,"[ERP139923, PRJEB55057]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2026-04-30T22:25:40.059000+00:00
6,MGYS00006208,"[ERP140115, PRJEB55232]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2026-04-30T22:01:49.848000+00:00
7,MGYS00010257,"[SRP456588, PRJNA1004080]",Combined effect of microplastics and fungicide...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-03T18:47:35.095000+00:00
8,MGYS00010258,"[SRP517058, PRJNA1127303]",Metagenomic data of rhizosphere soil during to...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-04T11:04:15.175000+00:00
9,MGYS00010324,[PRJEB95772],Metagenome assembly of PRJNA777724 data set (T...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-08-07T12:30:16.888000+00:00
10,MGYS00010245,"[PRJEB82447, ERP166136]",Unveiling diversity and adaptations of the wil...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-23T16:38:33.334000+00:00
11,MGYS00010298,"[PRJNA777724, SRP344777]",Tomato heritable microbiome,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-08-07T15:25:59.939000+00:00
12,MGYS00010262,[PRJEB91684],Metagenome assembly of PRJNA1004080 data set (...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-03T18:41:58.194000+00:00
13,MGYS00010250,"[PRJNA755741, SRP333163]",Tomato rhizosphere microbiome in the belowgrou...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-23T08:45:47.142000+00:00
14,MGYS00010264,[PRJEB91717],Metagenome assembly of PRJNA1127303 data set (...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-04T10:10:15.643000+00:00
15,MGYS00010251,"[SRP338795, PRJNA766489]",Culture-independent analysis of rhizosphere mi...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-21T17:01:18.132000+00:00
16,MGYS00010253,"[PRJNA789467, SRP351203]",Disentangling the genetic basis of rhizosphere...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-08-01T17:26:35.948000+00:00

## Getting the study details

From our filtered list of studies we can use `.get_detail()` to iteratively get their details from the [**get_mgnify_study** MGnify API endpoint](https://www.ebi.ac.uk/metagenomics/api/v2/#/Studies/get_mgnify_study)

In [7]:
while True:
    det = filtered_studies.get_detail()
    if det is None:  # no more details to fetch
        print("Finished fetching details for all studies.")
        break

Finished fetching details for all studies.

We can take a look at all study metadata details which are stored to

- `.collected_details`: the `mgnipy.StudyDetail` instances
- `.collected_details_rsults`: a dictionary where each item is a accession: detail
- `.collected_details_df`: a pd.DataFrame where each study metadata detail is a row

In [8]:
filtered_studies.collected_details_df

,accession,ena_accessions,title,biome,updated_at,downloads,metadata,first_accession
MGYS00010296,MGYS00010296,"[ERP166137, PRJEB82448]",Microbiome-mediated tolerance of wild tomato t...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T14:00:52.352000+00:00,[],{},ERP166137
MGYS00010297,MGYS00010297,"[SRP333165, PRJNA755742]",Tomato rhizosphere microbiome in the pot exper...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2025-07-23T11:42:02.227000+00:00,[],{},SRP333165
MGYS00006231,MGYS00006231,"[ERP139927, PRJEB55060]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2026-04-30T22:27:28.963000+00:00,"[{'file_type': 'tsv', 'download_type': 'Taxono...",{},ERP139927
MGYS00006204,MGYS00006204,"[ERP140102, PRJEB55219]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2026-04-30T22:01:19.102000+00:00,"[{'file_type': 'tsv', 'download_type': 'Taxono...",{},ERP140102
MGYS00006205,MGYS00006205,"[ERP140107, PRJEB55224]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2026-04-30T22:01:31.666000+00:00,"[{'file_type': 'tsv', 'download_type': 'Taxono...",{},ERP140107
MGYS00006230,MGYS00006230,"[ERP139923, PRJEB55057]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2026-04-30T22:25:40.059000+00:00,"[{'file_type': 'tsv', 'download_type': 'Taxono...",{},ERP139923
MGYS00006208,MGYS00006208,"[ERP140115, PRJEB55232]",EMG produced TPA metagenomics assembly of PRJN...,"{'biome_name': 'Rhizosphere', 'lineage': 'root...",2026-04-30T22:01:49.848000+00:00,"[{'file_type': 'tsv', 'download_type': 'Taxono...",{},ERP140115
MGYS00010257,MGYS00010257,"[SRP456588, PRJNA1004080]",Combined effect of microplastics and fungicide...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-03T18:47:35.095000+00:00,[],{},SRP456588
MGYS00010258,MGYS00010258,"[SRP517058, PRJNA1127303]",Metagenomic data of rhizosphere soil during to...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-04T11:04:15.175000+00:00,[],{},SRP517058
MGYS00010324,MGYS00010324,[PRJEB95772],Metagenome assembly of PRJNA777724 data set (T...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-08-07T12:30:16.888000+00:00,[],{},PRJEB95772
MGYS00010245,MGYS00010245,"[PRJEB82447, ERP166136]",Unveiling diversity and adaptations of the wil...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-23T16:38:33.334000+00:00,[],{},ERP166136
MGYS00010298,MGYS00010298,"[PRJNA777724, SRP344777]",Tomato heritable microbiome,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-08-07T15:25:59.939000+00:00,[],{},SRP344777
MGYS00010262,MGYS00010262,[PRJEB91684],Metagenome assembly of PRJNA1004080 data set (...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-03T18:41:58.194000+00:00,[],{},PRJEB91684
MGYS00010250,MGYS00010250,"[PRJNA755741, SRP333163]",Tomato rhizosphere microbiome in the belowgrou...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-23T08:45:47.142000+00:00,[],{},SRP333163
MGYS00010264,MGYS00010264,[PRJEB91717],Metagenome assembly of PRJNA1127303 data set (...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-04T10:10:15.643000+00:00,[],{},PRJEB91717
MGYS00010251,MGYS00010251,"[SRP338795, PRJNA766489]",Culture-independent analysis of rhizosphere mi...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-07-21T17:01:18.132000+00:00,[],{},SRP338795
MGYS00010253,MGYS00010253,"[PRJNA789467, SRP351203]",Disentangling the genetic basis of rhizosphere...,"{'biome_name': 'Soil', 'lineage': 'root:Host-a...",2025-08-01T17:26:35.948000+00:00,[],{},SRP351203

## Now getting analyses for the given studies

We can see what relationships

In [9]:
study_details = filtered_studies.collected_details

study_details["MGYS00010296"].list_relationships()

['samples', 'analyses', 'publications']

In [10]:
study_details["MGYS00010296"].analyses

Retrieving pages: 0it [00:00, ?it/s]